// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.Prologue.Extractor.Sources.Schema;

/// <summary>
/// Represents a single raw column row read from a database's catalog — one column of one table, in the
/// engine-neutral shape the schema readers produce and <see cref="SchemaObservationBuilder"/> consumes.
/// </summary>
/// <param name="Schema">The schema of the table the column belongs to.</param>
/// <param name="Table">The name of the table the column belongs to.</param>
/// <param name="Name">The name of the column.</param>
/// <param name="DataType">The engine-specific data type name.</param>
/// <param name="MaxLength">The declared maximum length for character and binary types; 0 when the column has no declared maximum.</param>
/// <param name="IsNullable">Whether the column accepts null.</param>
/// <param name="IsIdentity">Whether the column's value is generated by the database.</param>
/// <param name="DefaultExpression">The column's default value expression; empty when the column has no default.</param>
public record SchemaColumnRow(
    string Schema,
    string Table,
    string Name,
    string DataType,
    int MaxLength,
    bool IsNullable,
    bool IsIdentity,
    string DefaultExpression);
