// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.Prologue.Contracts;

/// <summary>
/// Represents a single column within an observed table — its data type, size, and whether the database requires
/// a value for it. No data values are captured.
/// </summary>
/// <param name="Name">The name of the column.</param>
/// <param name="DataType">The engine-specific data type name (for example <c>nvarchar</c> or <c>integer</c>).</param>
/// <param name="MaxLength">The declared maximum length for character and binary types; 0 when the column has no declared maximum (unbounded or not length-typed).</param>
/// <param name="IsNullable">Whether the column accepts null — a non-nullable column is a required field.</param>
/// <param name="IsIdentity">Whether the column's value is generated by the database (identity, serial, or equivalent).</param>
/// <param name="DefaultExpression">The column's default value expression; empty when the column has no default.</param>
public record SchemaColumn(
    string Name,
    string DataType,
    int MaxLength,
    bool IsNullable,
    bool IsIdentity,
    string DefaultExpression = "");
